version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yourdbname
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=customer_order_service.settings
      - NAME=yourdbname
      - USER=youruser
      - PASSWORD=yourpassword
      - HOST=db
      - PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: